#!/usr/bin/env python

import json
import os.path

include_paths = ["."]

if os.path.exists("/config.json"):
    contents = open("/config.json").read()
    config = json.loads(contents)

    if config.get("include_paths"):
        config_paths = config.get("include_paths")
        python_paths = []

        for i in config_paths:
            ext = os.path.splitext(i)[1]
            if os.path.isdir(i) or "py" in ext:
                python_paths.append(i)
        include_paths = python_paths

if len(include_paths) > 0:
    args = " ".join(include_paths)
    os.system("/usr/src/app/pep8.py --codeclimate {0}".format(args))
